/*
 * Loads auction data from infiles that were generated by 
 * MyParser program
 */

LOAD DATA LOCAL INFILE 'Item.dat' INTO TABLE Item 
	FIELDS TERMINATED BY "|*|" ;
LOAD DATA LOCAL INFILE 'User.dat' INTO TABLE AuctionUser 
	FIELDS TERMINATED BY "|*|" ;
LOAD DATA LOCAL INFILE 'Bid.dat' INTO TABLE Bid 
	FIELDS TERMINATED BY "|*|" ;
LOAD DATA LOCAL INFILE 'ItemCategory.dat' INTO TABLE ItemCategory 
	FIELDS TERMINATED BY "|*|" ;

